#!/usr/bin/env python3
"""Capture legacy extraction and persona outputs as golden files (BAS-03, ADR-023).

Writes tests/fixtures/legacy-golden/<fixture-name>.json for every file in
tests/fixtures/synthetic/ (README.md excluded). These files are the parity target
for the JavaScript ports (MIG-01A, MIG-02A). Do not edit them by hand; rerun:

    python3 -m venv /tmp/pdae-golden-venv
    /tmp/pdae-golden-venv/bin/pip install pyyaml
    /tmp/pdae-golden-venv/bin/python tools/legacy-golden.py

The script imports the legacy modules directly (no server, no AI backend), runs
with the current working directory set to a fresh temporary directory (legacy
admin/config.py uses a cwd-relative projects_data) and PROJECTS_DATA_DIR pointed
at that same directory, and never writes inside the repository except the
golden files. It re-executes itself once with PYTHONHASHSEED=0 so set ordering
inside legacy code is stable.

Call mapping (after reading the legacy signatures at the recorded commit):
  doc     = processors.ingestion.ingest_file(path).to_dict()
  extract = processors.extractors.intelligence_extractor.extract_intelligence(doc)
  context = processors.context_builder.build_context([doc], ai_backend="files_only")
  for each role in personas.engine.list_personas():
      review = personas.engine.run_review(role["id"], context, ai_backend="files_only")
      dive   = personas.deep_dive.run_deep_dive(role["name"],
                   scope=context.get("scope", ""), intelligence=context,
                   active_files=[], ai_backend="files_only")

Differences from the backlog's mapping (BAS-03), recorded as required:
  - list_personas() returns 12 *roles* (id == visible role name) across 6 persona
    groups; run_review takes the role name. Every role is captured, which covers
    every persona group. Reviews and deep dives are keyed by role name ("persona_id"
    is normalised away because it ends in _id).
  - extract_intelligence is called directly as well as through build_context, so
    the per-kind output of a single document is recorded without aggregation.
  - doc["file_path"] is absolute; it is replaced with "<fixture>/<name>". Any other
    occurrence of the temporary directory or repository path is replaced likewise.

Normalisation: values of keys named timestamp, created_at, updated_at,
generated_at, id, or ending in _id become "<normalised>" (this includes transcript
section timestamps). Keys ending in _at are normalised too: build_context adds a
"built_at" wall-clock time that the backlog's key list did not name. Lists are sorted (scalars by value, objects by their
canonical JSON) so parity tests compare sets. JSON is written with indent=2 and
sort_keys=True. The "ingest" entry is a summary: metadata plus per-section
heading, type, speaker, line range and character count (no section text).
"""

import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURES = REPO_ROOT / "tests" / "fixtures" / "synthetic"
OUT_DIR = REPO_ROOT / "tests" / "fixtures" / "legacy-golden"
GENERATED = "GENERATED by tools/legacy-golden.py – do not edit"
TIME_KEYS = {"timestamp", "created_at", "updated_at", "generated_at", "id"}
PLACEHOLDER = "<normalised>"


def legacy_commit():
    """Last commit that touched legacy code (stable across doc-only commits)."""
    paths = ["processors", "personas", "models", "admin", "ai_backends", "core"]
    out = subprocess.run(
        ["git", "log", "-1", "--format=%H", "--", *paths],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    )
    return out.stdout.strip()


def normalise(value, replacements):
    if isinstance(value, dict):
        out = {}
        for k, v in value.items():
            key = str(k)
            if key in TIME_KEYS or key.endswith("_id") or key.endswith("_at"):
                out[key] = PLACEHOLDER if v not in (None, "", [], {}) else v
            else:
                out[key] = normalise(v, replacements)
        return out
    if isinstance(value, (list, tuple, set)):
        items = [normalise(v, replacements) for v in value]
        return sorted(items, key=lambda x: json.dumps(x, sort_keys=True, ensure_ascii=False))
    if isinstance(value, str):
        for old, new in replacements:
            value = value.replace(old, new)
        return value
    return value


def ingest_summary(doc):
    return {
        "content_type": doc.get("content_type"),
        "is_valid": doc.get("is_valid"),
        "metadata": doc.get("metadata"),
        "sections": [
            {
                "heading": s.get("heading"),
                "section_type": s.get("section_type"),
                "speaker": s.get("speaker"),
                "timestamp": s.get("timestamp"),
                "line_start": s.get("line_start"),
                "line_end": s.get("line_end"),
                "content_chars": len(s.get("content") or ""),
            }
            for s in doc.get("sections", [])
        ],
        "section_count": len(doc.get("sections", [])),
    }


def generate(work_dir):
    sys.path.insert(0, str(REPO_ROOT))
    from processors.ingestion import ingest_file
    from processors.extractors.intelligence_extractor import extract_intelligence
    from processors.context_builder import build_context
    from personas.engine import list_personas, run_review
    from personas.deep_dive import run_deep_dive

    commit = legacy_commit()
    roles = list_personas()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for src in sorted(FIXTURES.iterdir()):
        if not src.is_file() or src.name == "README.md":
            continue
        # Copy into the temp dir so legacy code only ever sees a temp path.
        path = Path(work_dir) / "fixtures" / src.name
        path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, path)
        replacements = [
            (str(path), f"<fixture>/{src.name}"),
            (str(Path(work_dir).resolve()), "<tmp>"),
            (str(work_dir), "<tmp>"),
            (str(REPO_ROOT), "<repo>"),
        ]
        doc = ingest_file(path).to_dict()
        context = build_context([doc], ai_backend="files_only")
        reviews = {}
        deep_dives = {}
        for role in roles:
            reviews[role["id"]] = run_review(role["id"], context, ai_backend="files_only")
            deep_dives[role["name"]] = run_deep_dive(
                role["name"],
                scope=context.get("scope", ""),
                intelligence=context,
                active_files=[],
                ai_backend="files_only",
            )
        golden = {
            "_generated": GENERATED,
            "legacy_commit": commit,
            "fixture": src.name,
            "fixture_sha256": hashlib.sha256(src.read_bytes()).hexdigest(),
            "ingest": ingest_summary(doc),
            "extract_intelligence": extract_intelligence(doc),
            "build_context": context,
            "run_review": reviews,
            "run_deep_dive": deep_dives,
        }
        golden = normalise(golden, replacements)
        out = OUT_DIR / f"{src.name}.json"
        out.write_text(json.dumps(golden, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
        written.append(out.relative_to(REPO_ROOT).as_posix())
    return written


def main():
    if os.environ.get("PYTHONHASHSEED") != "0":
        env = dict(os.environ, PYTHONHASHSEED="0")
        sys.exit(subprocess.call([sys.executable, str(Path(__file__).resolve()), *sys.argv[1:]], env=env))
    work_dir = tempfile.mkdtemp(prefix="pdae-golden-")
    try:
        os.environ["PROJECTS_DATA_DIR"] = work_dir
        os.chdir(work_dir)
        written = generate(work_dir)
    finally:
        os.chdir(REPO_ROOT)
        shutil.rmtree(work_dir, ignore_errors=True)
    for w in written:
        print(f"wrote {w}")
    print(f"legacy-golden: {len(written)} file(s)")


if __name__ == "__main__":
    main()
